"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpRight, CalendarDays, Check, CheckCircle2, ChevronRight, Download, ExternalLink, FileSignature, FileText, Languages, Loader2, LockKeyhole, MessageSquare, ShieldCheck } from "lucide-react";
import { GandoMark } from "@/components/gando-mark";
import { SDRoomBrandBanner } from "@/components/sd-room-brand-banner";
import { SD_CODES, SD_STAGE_META, type SD01Content, type SDCode, type SDDocumentRecord, type SDRoomBrandTheme } from "@/lib/sd-room-types";
import type { SD02Content, SD03Content, SD04Content, SD05Content } from "@/lib/sd-stage-content";

type PublicDocument = SDDocumentRecord & { validated_at?: string | null; validated_by_first_name?: string | null; validated_by_last_name?: string | null };
type PublicRoomData = {
  room: { id: string; title: string; companyName: string; companyLogoUrl: string | null; bannerImageUrl: string | null; theme: SDRoomBrandTheme; displayTitle: string; displaySubtitle: string; meetingBookingUrl: string | null; currentStage: SDCode; updatedAt: string };
  documents: PublicDocument[];
  visitorEmail: string;
  visitorFirstName: string;
  visitorLastName: string;
};
type PublicComment = { id: string; documentCode: SDCode; sectionKey: string | null; authorEmail: string; authorFirstName: string | null; authorLastName: string | null; body: string; status: "open" | "resolved"; createdAt: string; resolvedAt: string | null };
type RoomLanguage = "fr" | "en";
const OPTIONAL_CODES: SDCode[] = ["SD03", "SD04"];
const tr = (language: RoomLanguage, fr: string, en: string) => language === "en" ? en : fr;

function formatDate(value?: string | null, language: RoomLanguage = "fr") {
  if (!value) return "";
  try { return new Intl.DateTimeFormat(language === "en" ? "en-GB" : "fr-FR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(value)); } catch { return value; }
}
function stageTitle(code: SDCode, language: RoomLanguage) {
  if (language === "en") return ({ SD01: "Summary", SD02: "Next steps", SD03: "Solution & integration", SD04: "Commercial proposal", SD05: "Contract & signature" } as Record<SDCode, string>)[code];
  return SD_STAGE_META[code].title;
}
function preferredOpeningStage(documents: PublicDocument[]): SDCode {
  return documents.find(document => document.status === "published")?.code || documents.find(document => document.status === "validated")?.code || documents[0]?.code || "SD01";
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#687277]">{children}</div>; }
function Section({ title, children, kicker }: { title: string; children: React.ReactNode; kicker?: string }) { return <section className="rounded-[18px] border border-[#e0e4e6] bg-white px-5 py-6 shadow-[0_1px_2px_rgba(20,30,35,0.025)] sm:px-8 sm:py-8">{kicker ? <Eyebrow>{kicker}</Eyebrow> : null}<h2 className="mt-1 text-[21px] font-semibold tracking-[-0.025em] text-[#172126] sm:text-[23px]">{title}</h2><div className="mt-5 text-[15px] leading-7 text-[#465157]">{children}</div></section>; }
function BulletList({ items, empty = "À confirmer" }: { items?: string[]; empty?: string }) { if (!items?.length) return <p className="italic text-[#81898e]">{empty}</p>; return <ul className="space-y-3">{items.map((item, index) => <li key={`${index}-${item}`} className="flex gap-3"><span className="mt-[10px] h-1.5 w-1.5 shrink-0 rounded-full bg-[#7166c7]" /><span>{item}</span></li>)}</ul>; }

function SD01Document({ content, language }: { content: SD01Content; language: RoomLanguage }) {
  const metrics = (content.roi?.valueLevers || []).filter(metric => metric.value?.trim());
  return <div className="space-y-5 sm:space-y-6">
    <Section title={tr(language, "Synthèse exécutive", "Executive summary")} kicker={tr(language, "SD01 · Compréhension commune", "SD01 · Shared understanding")}><p className="text-[18px] font-medium leading-8 text-[#202a2f]">{content.executiveSummary || tr(language, "Synthèse en cours de validation.", "Summary pending approval.")}</p></Section>
    {(content.companyProfile?.sector || content.companyProfile?.description || content.companyProfile?.context) ? <Section title={tr(language, "Entreprise & contexte", "Company & context")}><div className="grid gap-5 sm:grid-cols-[170px_1fr]"><div><Eyebrow>{tr(language, "Secteur", "Industry")}</Eyebrow><div className="mt-2 font-semibold text-[#202a2f]">{content.companyProfile?.sector || tr(language, "À confirmer", "TBD")}</div></div><div><Eyebrow>{tr(language, "Entreprise", "Company")}</Eyebrow><p className="mt-2">{content.companyProfile?.description || tr(language, "À compléter", "To complete")}</p></div></div>{content.companyProfile?.context ? <p className="mt-5 border-t border-[#eceeef] pt-5">{content.companyProfile.context}</p> : null}</Section> : null}
    {content.stakeholders?.length ? <Section title={tr(language, "Personnes clés", "Key people")}><div className="grid gap-3 sm:grid-cols-2">{content.stakeholders.map((person, index) => <div key={index} className="rounded-xl bg-[#f6f7f8] p-4"><div className="font-semibold text-[#202a2f]">{person.name}</div><div className="mt-1 text-[13px] text-[#687277]">{person.role}{person.organization ? ` · ${person.organization}` : ""}</div>{person.notes ? <p className="mt-2 text-[13px] leading-6 text-[#687277]">{person.notes}</p> : null}</div>)}</div></Section> : null}
    {content.currentProcess?.length ? <Section title={tr(language, "Processus actuel", "Current process")}><BulletList items={content.currentProcess} /></Section> : null}
    {(content.productsAndOffers?.length || content.businessModel?.length) ? <Section title={tr(language, "Offre & modèle actuel", "Current offer & model")}><div className="grid gap-6 sm:grid-cols-2"><div><Eyebrow>{tr(language, "Produits / offres", "Products / offers")}</Eyebrow><div className="mt-3"><BulletList items={content.productsAndOffers} /></div></div><div><Eyebrow>{tr(language, "Business model", "Business model")}</Eyebrow><div className="mt-3"><BulletList items={content.businessModel} /></div></div></div></Section> : null}
    <Section title={tr(language, "Enjeux prioritaires", "Top priorities")}>{content.painPoints?.length ? <div className="space-y-5">{content.painPoints.map((pain, index) => <div key={index} className="border-b border-[#eceeef] pb-5 last:border-0 last:pb-0"><div className="font-semibold text-[#202a2f]">{pain.title}</div><div className="mt-2"><BulletList items={pain.details} /></div></div>)}</div> : <p className="italic text-[#81898e]">{tr(language, "Enjeux à préciser.", "Priorities to clarify.")}</p>}</Section>
    {content.solutionFit?.length ? <Section title={tr(language, "Solution fit", "Solution fit")} kicker={tr(language, "Besoin → réponse proposée", "Need → proposed response")}><div className="divide-y divide-[#eceeef]">{content.solutionFit.map((item, index) => <div key={index} className="grid gap-3 py-4 first:pt-0 last:pb-0 md:grid-cols-2"><div className="font-semibold text-[#202a2f]">{item.need}</div><div>{item.response}</div></div>)}</div></Section> : null}
    {metrics.length ? <Section title={tr(language, "Métriques confirmées", "Confirmed metrics")}><div className="grid gap-3 sm:grid-cols-2">{metrics.map((metric, index) => <div key={index} className="rounded-xl bg-[#f3f0ff] p-4"><Eyebrow>{metric.lever}</Eyebrow><div className="mt-2 text-[24px] font-semibold tracking-[-0.03em] text-[#4d438f]">{metric.value}</div>{metric.mechanism ? <p className="mt-1 text-[13px] leading-6 text-[#6a6487]">{metric.mechanism}</p> : null}</div>)}</div></Section> : null}
    {content.urgency?.length ? <Section title={tr(language, "Pourquoi maintenant ?", "Why now?")}><BulletList items={content.urgency} /></Section> : null}
  </div>;
}

function statusLabel(status: string, language: RoomLanguage) { return status === "done" ? tr(language, "Terminé", "Done") : status === "in_progress" ? tr(language, "En cours", "In progress") : tr(language, "À faire", "To do"); }
function SD02Document({ content, language }: { content: SD02Content; language: RoomLanguage }) {
  const steps = content.milestones || [];
  return <div className="space-y-5 sm:space-y-6">
    {content.objective ? <Section title={tr(language, "Objectif partagé", "Shared objective")} kicker={tr(language, "SD02 · Prochaines étapes", "SD02 · Next steps")}><p className="text-[18px] font-medium leading-8 text-[#202a2f]">{content.objective}</p></Section> : null}
    {(content.decisionProcess?.length || content.blockers?.length) ? <Section title={tr(language, "Décisions & points à trancher", "Decisions & open points")}><div className="grid gap-7 md:grid-cols-2"><div><Eyebrow>{tr(language, "Décisions actées", "Decisions made")}</Eyebrow><div className="mt-3"><BulletList items={content.decisionProcess} /></div></div><div><Eyebrow>{tr(language, "Points à trancher", "Open points")}</Eyebrow><div className="mt-3"><BulletList items={content.blockers} /></div></div></div></Section> : null}
    <Section title={tr(language, "Prochaines étapes", "Next steps")} kicker={tr(language, "Plan d’action partagé", "Shared action plan")}>{steps.length ? <div className="relative"><div className="absolute bottom-8 left-[15px] top-8 w-px bg-[#d9dde0] sm:left-[19px]" /><div className="space-y-4">{steps.map((item, index) => <article key={`${item.milestone}-${index}`} className="relative grid grid-cols-[32px_1fr] gap-3 sm:grid-cols-[40px_1fr] sm:gap-4"><div className="relative z-10 mt-4 grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-[#6e62c3] font-mono text-[10px] font-semibold text-white shadow-sm sm:h-10 sm:w-10">{String(index + 1).padStart(2, "0")}</div><div className="rounded-[14px] border border-[#e1e5e7] bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="text-[17px] font-semibold leading-6 text-[#202a2f]">{item.milestone}</h3><span className="rounded-full bg-[#f3f0ff] px-2.5 py-1 text-[11px] font-semibold text-[#5c50ae]">{statusLabel(item.status, language)}</span></div><div className="mt-4 grid gap-3 border-t border-[#eceeef] pt-4 text-[13px] sm:grid-cols-2"><div><Eyebrow>{tr(language, "Responsable", "Owner")}</Eyebrow><div className="mt-1 font-medium text-[#4c565b]">{item.owner || tr(language, "À définir", "TBD")}</div></div><div><Eyebrow>{tr(language, "Échéance", "Due date")}</Eyebrow><div className="mt-1 font-medium text-[#4c565b]">{formatDate(item.dueDate, language) || tr(language, "À définir", "TBD")}</div></div></div>{item.dependency ? <p className="mt-3 rounded-lg bg-[#f6f7f8] px-3 py-2 text-[12px] text-[#687277]">{item.dependency}</p> : null}</div></article>)}</div></div> : <p className="italic text-[#81898e]">{tr(language, "Aucune étape définie.", "No step defined yet.")}</p>}</Section>
  </div>;
}

function SD03Document({ content, language }: { content: SD03Content; language: RoomLanguage }) { return <div className="space-y-5"><Section title={tr(language, "Solution retenue", "Selected solution")} kicker="SD03"><p className="text-[18px] font-medium leading-8 text-[#202a2f]">{content.solutionSummary || tr(language, "Solution à finaliser.", "Solution to finalize.")}</p></Section><Section title={tr(language, "Périmètre", "Scope")}><div className="grid gap-7 md:grid-cols-2"><div><Eyebrow>{tr(language, "Inclus", "Included")}</Eyebrow><div className="mt-3"><BulletList items={content.scopeIn} /></div></div><div><Eyebrow>{tr(language, "Hors périmètre", "Out of scope")}</Eyebrow><div className="mt-3"><BulletList items={content.scopeOut} /></div></div></div></Section></div>; }
function SD04Document({ content, language }: { content: SD04Content; language: RoomLanguage }) { const pdfUrl = /^https?:\/\//i.test(content.deckSubtitle || "") ? content.deckSubtitle : ""; return <Section title={content.deckTitle || tr(language, "Proposition commerciale", "Commercial proposal")} kicker="SD04">{pdfUrl ? <div className="overflow-hidden rounded-[16px] border border-[#d9dee1] bg-[#eef0f2]"><div className="flex items-center gap-3 bg-[#20282d] px-4 py-3 text-white"><FileText className="h-4 w-4" /><div className="min-w-0 flex-1 truncate text-sm font-semibold">{content.deckTitle || "Document commercial"}</div><a href={pdfUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold"><ExternalLink className="h-3.5 w-3.5" />{tr(language, "Ouvrir", "Open")}</a></div><iframe src={`${pdfUrl.split("#")[0]}#toolbar=0&navpanes=0&view=FitH`} title="PDF" className="hidden h-[780px] w-full bg-white md:block" /></div> : <p className="italic text-[#81898e]">{tr(language, "Aucun PDF publié.", "No PDF published.")}</p>}</Section>; }
function SD05Document({ content, token, visitorEmail, language, status }: { content: SD05Content; token: string; visitorEmail: string; language: RoomLanguage; status: string }) { const signed = content.contractStatus === "signed" || status === "validated"; return <Section title={content.contractTitle || tr(language, "Contrat", "Contract")} kicker="SD05"><div className="flex flex-col gap-4"><span className="w-fit rounded-full bg-[#f3f0ff] px-3 py-1.5 text-[12px] font-semibold text-[#5c50ae]">{signed ? tr(language, "Signé", "Signed") : content.contractStatus === "ready_to_sign" ? tr(language, "Prêt à signer", "Ready to sign") : tr(language, "En préparation", "In preparation")}</span>{content.contractSummary ? <p>{content.contractSummary}</p> : null}<div className="flex flex-wrap gap-2">{content.contractUrl ? <a href={content.contractUrl} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#202a2f] px-5 text-[13px] font-semibold text-white"><FileSignature className="h-4 w-4" />{tr(language, "Ouvrir le contrat", "Open contract")}</a> : null}{status === "validated" ? <a href={`/api/public/deal-room/${encodeURIComponent(token)}/sd05-pdf?email=${encodeURIComponent(visitorEmail)}`} className="inline-flex h-11 items-center gap-2 rounded-xl border border-[#ccd2d5] bg-white px-5 text-[13px] font-semibold text-[#202a2f]"><Download className="h-4 w-4" />PDF</a> : null}</div></div></Section>; }
function DocumentBody({ document, token, visitorEmail, language }: { document: PublicDocument; token: string; visitorEmail: string; language: RoomLanguage }) { if (document.code === "SD01") return <SD01Document content={document.content as SD01Content} language={language} />; if (document.code === "SD02") return <SD02Document content={document.content as unknown as SD02Content} language={language} />; if (document.code === "SD03") return <SD03Document content={document.content as unknown as SD03Content} language={language} />; if (document.code === "SD04") return <SD04Document content={document.content as unknown as SD04Content} language={language} />; return <SD05Document content={document.content as unknown as SD05Content} token={token} visitorEmail={visitorEmail} language={language} status={document.status} />; }

function AccessGate({ firstName, lastName, email, setFirstName, setLastName, setEmail, loading, error, onSubmit, language, setLanguage }: { firstName: string; lastName: string; email: string; setFirstName: (value: string) => void; setLastName: (value: string) => void; setEmail: (value: string) => void; loading: boolean; error: string; onSubmit: (event: React.FormEvent) => void; language: RoomLanguage; setLanguage: (language: RoomLanguage) => void }) {
  const inputClass = "mt-2 h-11 w-full rounded-xl border border-[#cbd2d6] bg-white px-3.5 text-[15px] text-black outline-none focus:border-[#7b6fd0] focus:ring-2 focus:ring-[#7568cf]/10";
  return <main className="min-h-screen bg-[#f5f6f7] px-5 py-8 text-[#111] sm:px-8 sm:py-12"><div className="mx-auto max-w-[760px]"><header className="flex items-center justify-between"><div className="flex items-center gap-2.5"><GandoMark className="h-8 w-8" /><span className="text-sm font-semibold">Gando</span></div><div className="inline-flex rounded-lg border border-[#d9dde0] bg-white p-0.5 text-[11px] font-semibold"><button onClick={() => setLanguage("fr")} className={`rounded-md px-2 py-1 ${language === "fr" ? "bg-[#202a2f] text-white" : "text-[#4e585d]"}`}>FR</button><button onClick={() => setLanguage("en")} className={`rounded-md px-2 py-1 ${language === "en" ? "bg-[#202a2f] text-white" : "text-[#4e585d]"}`}>EN</button></div></header><form onSubmit={onSubmit} className="mt-10 rounded-[22px] border border-[#d8dde0] bg-white p-6 shadow-[0_18px_55px_rgba(30,40,45,0.06)] sm:p-8"><Eyebrow>{tr(language, "Accéder à la Room", "Access the Room")}</Eyebrow><h1 className="mt-2 text-[34px] font-semibold tracking-[-0.04em]">{tr(language, "Identifiez-vous", "Identify yourself")}</h1><p className="mt-3 text-[15px] leading-7 text-[#4f595e]">{tr(language, "Vos informations permettent d’attribuer les remarques et validations.", "Your information is used to attribute comments and approvals.")}</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">{tr(language, "Prénom", "First name")}<input required value={firstName} onChange={event => setFirstName(event.target.value)} className={inputClass} /></label><label className="text-xs font-semibold">{tr(language, "Nom", "Last name")}<input required value={lastName} onChange={event => setLastName(event.target.value)} className={inputClass} /></label></div><label className="mt-4 block text-xs font-semibold">Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} className={inputClass} /></label>{error ? <p className="mt-4 rounded-xl bg-[#fff3f1] px-3.5 py-3 text-[13px] text-[#9a4137]">{error}</p> : null}<button type="submit" disabled={loading} className="mt-6 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#202a2f] px-4 text-[14px] font-semibold text-white disabled:opacity-55">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : null}{tr(language, "Entrer dans la Room", "Enter the Room")}<ChevronRight className="h-4 w-4" /></button><div className="mt-4 flex items-center justify-center gap-2 text-[12px] text-[#687277]"><ShieldCheck className="h-4 w-4 text-[#6558c8]" />{tr(language, "Accès identifié et confidentiel", "Identified and confidential access")}</div></form></div></main>;
}

export function PublicSDRoomV7({ token }: { token: string }) {
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [email, setEmail] = useState(""); const [language, setLanguage] = useState<RoomLanguage>("fr");
  const [data, setData] = useState<PublicRoomData | null>(null); const [activeStage, setActiveStage] = useState<SDCode>("SD01"); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [sessionId, setSessionId] = useState(""); const [comment, setComment] = useState(""); const [comments, setComments] = useState<PublicComment[]>([]); const [commentState, setCommentState] = useState<"idle" | "sending" | "sent">("idle"); const [validating, setValidating] = useState(false); const openedRef = useRef(false);

  useEffect(() => { const sid = sessionStorage.getItem(`gando-room-session:${token}`) || crypto.randomUUID(); sessionStorage.setItem(`gando-room-session:${token}`, sid); setSessionId(sid); setFirstName(sessionStorage.getItem(`gando-room-first:${token}`) || ""); setLastName(sessionStorage.getItem(`gando-room-last:${token}`) || ""); setEmail(sessionStorage.getItem(`gando-room-email:${token}`) || ""); setLanguage(new URLSearchParams(window.location.search).get("lang") === "en" ? "en" : "fr"); }, [token]);
  const changeLanguage = useCallback((next: RoomLanguage) => { setLanguage(next); const url = new URL(window.location.href); if (next === "en") url.searchParams.set("lang", "en"); else url.searchParams.delete("lang"); window.history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`); }, []);
  const visitorEmail = data?.visitorEmail || "";
  const track = useCallback((eventType: string, documentCode: SDCode | null, activeSeconds = 0) => { if (!visitorEmail || !sessionId) return; void fetch(`/api/public/deal-room/${encodeURIComponent(token)}/events`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: visitorEmail, sessionId, eventType, documentCode, activeSeconds, metadata: { firstName, lastName } }), keepalive: true }); }, [firstName, lastName, sessionId, token, visitorEmail]);

  const loadComments = useCallback(async (documentCode: SDCode) => { if (!data?.visitorEmail || !firstName || !lastName) return; try { const params = new URLSearchParams({ email: data.visitorEmail, firstName, lastName, documentCode }); const response = await fetch(`/api/public/deal-room/${encodeURIComponent(token)}/comments?${params}`, { cache: "no-store" }); const payload = await response.json(); if (response.ok) setComments(payload.comments || []); } catch { setComments([]); } }, [data?.visitorEmail, firstName, lastName, token]);

  const unlock = async (event: React.FormEvent) => { event.preventDefault(); if (!firstName.trim() || !lastName.trim() || !email.trim()) return; setLoading(true); setError(""); try { const response = await fetch(`/api/public/deal-room/${encodeURIComponent(token)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ firstName: firstName.trim(), lastName: lastName.trim(), email: email.trim() }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Accès impossible"); const documents = payload.documents as PublicDocument[]; setData(payload); setActiveStage(preferredOpeningStage(documents)); sessionStorage.setItem(`gando-room-first:${token}`, firstName.trim()); sessionStorage.setItem(`gando-room-last:${token}`, lastName.trim()); sessionStorage.setItem(`gando-room-email:${token}`, payload.visitorEmail || email.trim()); } catch (unlockError) { setError(unlockError instanceof Error ? unlockError.message : "Accès impossible"); } finally { setLoading(false); } };
  useEffect(() => { if (!data || !sessionId || openedRef.current) return; openedRef.current = true; track("room_opened", activeStage); }, [activeStage, data, sessionId, track]);
  useEffect(() => { if (data && sessionId) { track("stage_viewed", activeStage); void loadComments(activeStage); } }, [activeStage, data, loadComments, sessionId, track]);
  useEffect(() => { if (!data || !sessionId) return; const interval = window.setInterval(() => { if (document.visibilityState === "visible") track("heartbeat", activeStage, 30); }, 30000); return () => window.clearInterval(interval); }, [activeStage, data, sessionId, track]);

  const currentDocument = data?.documents.find(document => document.code === activeStage) || data?.documents[0];
  const stages = useMemo(() => SD_CODES.map(code => ({ code, document: data?.documents.find(document => document.code === code) })), [data]);
  const sendComment = async (event: React.FormEvent) => { event.preventDefault(); if (!comment.trim() || !data || !currentDocument) return; setCommentState("sending"); try { const response = await fetch(`/api/public/deal-room/${encodeURIComponent(token)}/comments`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: data.visitorEmail, firstName, lastName, documentCode: currentDocument.code, sectionKey: currentDocument.code.toLowerCase(), body: comment.trim() }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Remarque non enregistrée"); setComment(""); setCommentState("sent"); await loadComments(currentDocument.code); window.setTimeout(() => setCommentState("idle"), 2200); } catch { setCommentState("idle"); } };
  const validateStage = async () => { if (!data || !currentDocument || currentDocument.status !== "published") return; setValidating(true); try { const response = await fetch(`/api/public/deal-room/${encodeURIComponent(token)}/validate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: data.visitorEmail, firstName, lastName, documentCode: currentDocument.code }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Validation impossible"); setData(current => current ? { ...current, documents: current.documents.map(document => document.code === currentDocument.code ? payload.document : document) } : current); } finally { setValidating(false); } };

  if (!data) return <AccessGate firstName={firstName} lastName={lastName} email={email} setFirstName={setFirstName} setLastName={setLastName} setEmail={setEmail} loading={loading} error={error} onSubmit={unlock} language={language} setLanguage={changeLanguage} />;
  if (!currentDocument) return <main className="grid min-h-screen place-items-center bg-[#f5f6f7] text-center"><div><h1 className="text-2xl font-semibold">Room en préparation</h1><p className="mt-2 text-[#6f787d]">Aucune étape publiée.</p></div></main>;
  const validatedBy = [currentDocument.validated_by_first_name, currentDocument.validated_by_last_name].filter(Boolean).join(" ");

  return <main className="min-h-screen bg-[#f5f6f7] text-[#1c2529]"><header className="sticky top-0 z-50 border-b border-[#e4e7e9] bg-white/95 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-[1180px] items-center gap-4 px-5 sm:px-7"><div className="flex min-w-0 items-center gap-2.5"><GandoMark className="h-8 w-8" /><span className="hidden text-sm font-semibold sm:inline">Gando</span><span className="text-[#b5bbc0]">/</span><span className="truncate text-sm font-medium text-[#4c565b]">{data.room.companyName}</span></div><div className="ml-auto flex items-center gap-2"><Languages className="h-3.5 w-3.5 text-[#737c81]" /><button onClick={() => changeLanguage(language === "fr" ? "en" : "fr")} className="rounded-lg border border-[#dfe3e5] bg-white px-2 py-1 text-[11px] font-semibold">{language === "fr" ? "EN" : "FR"}</button><LockKeyhole className="hidden h-3.5 w-3.5 text-[#737c81] sm:block" /></div></div></header>
    <SDRoomBrandBanner companyName={data.room.companyName} logoUrl={data.room.companyLogoUrl} bannerUrl={data.room.bannerImageUrl} theme={data.room.theme} title={data.room.displayTitle || `${data.room.companyName} × Gando`} subtitle={language === "en" ? "Collaboration space" : (data.room.displaySubtitle || "Espace de collaboration")} className="border-b border-[#e1e4e6]" />
    <div className="mx-auto grid max-w-[1180px] gap-8 px-5 py-9 sm:px-7 lg:grid-cols-[245px_minmax(0,790px)] lg:justify-between lg:py-12"><aside className="lg:sticky lg:top-24 lg:self-start"><Eyebrow>{tr(language, "Parcours", "Journey")}</Eyebrow><nav className="mt-4 space-y-1.5">{stages.map(({ code, document }) => { const active = code === currentDocument.code; const enabled = Boolean(document); const optional = OPTIONAL_CODES.includes(code); return <button key={code} type="button" disabled={!enabled} onClick={() => enabled && setActiveStage(code)} className={`flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left transition ${active ? "bg-white shadow-sm ring-1 ring-[#e0e4e6]" : enabled ? "hover:bg-white" : "opacity-40"}`}><span className={`mt-0.5 font-mono text-[11px] font-semibold ${active ? "text-[#584ead]" : "text-[#7f888d]"}`}>{code.slice(2)}</span><span className="min-w-0 flex-1"><span className="block text-[13px] font-semibold leading-5 text-[#505b60]">{stageTitle(code, language)}</span><span className="mt-0.5 block text-[11px] text-[#747e83]">{optional ? tr(language, "Facultatif", "Optional") : tr(language, "Obligatoire", "Required")} · {document?.status === "validated" ? tr(language, "Validé", "Approved") : document?.status === "published" ? tr(language, "À valider", "To approve") : tr(language, "À venir", "Upcoming")}</span></span>{document?.status === "validated" ? <CheckCircle2 className="h-4 w-4 text-[#4f835e]" /> : active ? <ChevronRight className="h-4 w-4 text-[#6558c8]" /> : null}</button>; })}</nav></aside>
      <article className="min-w-0"><div className="mb-7 flex items-center justify-between gap-4 border-b border-[#dfe3e5] pb-5"><div><Eyebrow>{currentDocument.code}</Eyebrow><h2 className="mt-1 text-[30px] font-semibold tracking-[-0.035em] text-[#182227]">{stageTitle(currentDocument.code, language)}</h2></div></div><DocumentBody document={currentDocument} token={token} visitorEmail={data.visitorEmail} language={language} />
        {currentDocument.code === "SD01" && data.room.meetingBookingUrl ? <section className="mt-6 rounded-[18px] bg-[#202a2f] p-5 text-white sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Eyebrow>{tr(language, "Prise de rendez-vous", "Schedule")}</Eyebrow><h3 className="mt-1 text-xl font-semibold">{tr(language, "Planifier le prochain échange", "Schedule the next discussion")}</h3></div><a href={data.room.meetingBookingUrl} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-white px-5 text-[13px] font-semibold text-[#202a2f]"><CalendarDays className="h-4 w-4" />{tr(language, "Réserver", "Book")}</a></div></section> : null}
        <section className="mt-7 rounded-[18px] border border-[#dfe3e5] bg-white p-5 sm:p-7">{currentDocument.status === "validated" ? <div className="flex gap-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#e8f2ea] text-[#3d7049]"><Check className="h-5 w-5" /></div><div><div className="font-semibold">{tr(language, "Cette étape est validée", "This stage is approved")}</div><p className="mt-1 text-[14px] text-[#687277]">{validatedBy || tr(language, "Validation enregistrée", "Approval recorded")}</p></div></div> : <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Eyebrow>{tr(language, "Validation", "Approval")}</Eyebrow><h3 className="mt-1 text-[20px] font-semibold">{tr(language, "Confirmez-vous cette étape ?", "Do you approve this stage?")}</h3></div><button onClick={() => void validateStage()} disabled={validating || currentDocument.status !== "published"} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#202a2f] px-5 text-[13px] font-semibold text-white disabled:opacity-45">{validating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}{tr(language, "Valider", "Approve")}</button></div>}</section>
        <section className="mt-5 rounded-[18px] border border-[#dedaf7] bg-[#f8f7ff] p-5 sm:p-7"><div className="flex items-center gap-2"><MessageSquare className="h-4 w-4 text-[#6558c8]" /><h3 className="text-[15px] font-semibold">{tr(language, "Remarques", "Comments")}</h3><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-semibold text-[#6558c8]">{comments.length}</span></div><div className="mt-4 space-y-2">{comments.map(item => { const author = [item.authorFirstName, item.authorLastName].filter(Boolean).join(" ") || item.authorEmail; return <div key={item.id} className={`rounded-xl border bg-white p-4 ${item.status === "resolved" ? "opacity-60" : "border-[#dedaf7]"}`}><div className="flex items-center justify-between gap-3 text-[11px]"><span className="font-semibold text-[#384247]">{author}</span><span className="text-[#848c90]">{item.status === "resolved" ? tr(language, "Traitée", "Resolved") : formatDate(item.createdAt, language)}</span></div><p className="mt-2 whitespace-pre-line text-[14px] leading-6 text-[#566166]">{item.body}</p></div>; })}{!comments.length ? <p className="text-[13px] italic text-[#81898e]">{tr(language, "Aucune remarque pour le moment.", "No comments yet.")}</p> : null}</div><form onSubmit={sendComment} className="mt-4 border-t border-[#e4e1f4] pt-4"><textarea value={comment} onChange={event => setComment(event.target.value)} rows={3} placeholder={tr(language, "Ajouter une remarque…", "Add a comment…")} className="w-full resize-y rounded-xl border border-[#d5dade] bg-white px-3.5 py-3 text-[15px] leading-6 outline-none focus:border-[#776bd0]" /><div className="mt-3 flex items-center justify-between"><span className="text-[11px] text-[#687277]">{firstName} {lastName}</span><button type="submit" disabled={!comment.trim() || commentState === "sending"} className="inline-flex h-9 items-center gap-2 rounded-lg bg-white px-3.5 text-[12px] font-semibold ring-1 ring-[#cfd4d7] disabled:opacity-50">{commentState === "sending" ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : commentState === "sent" ? <Check className="h-3.5 w-3.5" /> : <ArrowUpRight className="h-3.5 w-3.5" />}{commentState === "sent" ? tr(language, "Envoyé", "Sent") : tr(language, "Envoyer", "Send")}</button></div></form></section>
      </article></div><footer className="border-t border-[#dfe3e5] bg-white px-5 py-7 text-center text-[11px] text-[#848c90]">{tr(language, "Document confidentiel", "Confidential document")} · {data.room.companyName} × Gando</footer></main>;
}
