"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ExternalLink, Loader2, LockKeyhole, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { SDRoomBrandBanner } from "@/components/sd-room-brand-banner";
import { SD_CODES, SD_STAGE_META, type SDCode, type SDDocumentRecord, type SDRoomRecord } from "@/lib/sd-room-types";

type PreviewResponse = { room: SDRoomRecord | null; documents: SDDocumentRecord[]; message?: string; error?: string };
const OPTIONAL = new Set<SDCode>(["SD03", "SD04"]);

export function SDRoomPreview({ dealId }: { dealId: string }) {
  const [data, setData] = useState<PreviewResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/deals/${encodeURIComponent(dealId)}/sd-room`, { cache: "no-store" }); const payload = await response.json() as PreviewResponse; if (!response.ok) throw new Error(payload.message || payload.error || "Impossible de charger l’aperçu."); setData(payload); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Impossible de charger l’aperçu."); } finally { setLoading(false); } }, [dealId]);
  useEffect(() => { void load(); }, [load]);
  const room = data?.room;
  const publicDocuments = useMemo(() => (data?.documents || []).filter(document => document.status === "published" || document.status === "validated"), [data]);
  const shareUrl = room && typeof window !== "undefined" ? `${window.location.origin}/r/${room.share_token}` : "";
  if (loading) return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;
  if (error || !room || !data) return <div className="mx-auto max-w-2xl p-6"><Card className="p-8 text-center"><p className="text-sm text-destructive">{error || "Créez d’abord la Room SD."}</p><Button variant="outline" className="mt-4" onClick={() => void load()}><RefreshCw className="mr-2 h-4 w-4" /> Réessayer</Button></Card></div>;

  const firstCode = publicDocuments[0]?.code || "SD01";
  return <div className="min-h-screen bg-[#f5f6f7] p-5 lg:p-7"><div className="mx-auto max-w-[1380px] space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-primary">Prévisualisation</div><h1 className="mt-1 text-2xl font-bold tracking-[-0.035em]">Page client de la Room</h1><p className="mt-1 text-sm text-muted-foreground">La bannière ci-dessous est exactement celle du Branding et du site public.</p></div><Button asChild disabled={room.status !== "published"}><a href={shareUrl || "#"} target="_blank" rel="noreferrer"><ExternalLink className="mr-2 h-4 w-4" /> Ouvrir la Room réelle</a></Button></div>
    <div className="overflow-hidden rounded-[18px] border border-[#dfe3e5] bg-[#f5f6f7] shadow-[0_18px_60px_rgba(30,40,45,0.08)]"><div className="flex items-center gap-2 border-b border-[#e3e6e8] bg-white px-4 py-3"><span className="h-2.5 w-2.5 rounded-full bg-[#d5dade]" /><span className="h-2.5 w-2.5 rounded-full bg-[#d5dade]" /><span className="h-2.5 w-2.5 rounded-full bg-[#d5dade]" /><div className="mx-auto flex max-w-xl flex-1 items-center justify-center rounded-lg bg-[#f2f4f5] px-3 py-1.5 text-[11px] text-[#777f84]"><LockKeyhole className="mr-1.5 h-3 w-3" /> /r/{room.share_token.slice(0, 10)}…</div></div>
      <SDRoomBrandBanner companyName={room.company_name} logoUrl={room.prospect_logo_url} bannerUrl={room.brand_banner_image_url} theme={room.brand_theme} title={room.brand_title || room.title} subtitle={room.brand_subtitle || "Espace de collaboration stratégique"} className="min-h-[300px]" />
      <div className="grid gap-7 px-6 py-8 sm:px-8 lg:grid-cols-[220px_1fr]"><aside><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#777f84]">Parcours</div><div className="mt-3 space-y-1">{SD_CODES.map(code => { const document = data.documents.find(item => item.code === code); const visible = document?.status === "published" || document?.status === "validated"; const optional = OPTIONAL.has(code); return <div key={code} className={`flex items-start gap-2.5 rounded-lg px-2.5 py-2.5 ${code === firstCode ? "bg-white ring-1 ring-[#e0e4e6]" : ""} ${visible ? "" : "opacity-50"}`}><span className="font-mono text-[10px] font-semibold text-[#6b5fc8]">{code.slice(2)}</span><div className="min-w-0 flex-1"><div className="text-[11px] font-semibold leading-4 text-[#3f494e]">{SD_STAGE_META[code].title}</div><div className="mt-0.5 text-[9px] text-[#8a9296]">{optional ? "Facultatif" : "Obligatoire"} · {document?.status === "validated" ? "Validé" : visible ? "À valider" : "À venir"}</div></div>{document?.status === "validated" ? <CheckCircle2 className="h-3.5 w-3.5 text-[#4f835e]" /> : null}</div>; })}</div></aside><div><div className="mb-5 border-b border-[#dfe3e5] pb-4"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#737b80]">{firstCode}</div><h3 className="mt-1 text-[24px] font-semibold tracking-[-0.03em] text-[#182227]">{SD_STAGE_META[firstCode].title}</h3></div>{firstCode === "SD02" ? <div className="rounded-[16px] border border-[#e1e4e6] bg-white p-5"><div className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#737b80]">Plan d’action</div><div className="mt-4 overflow-hidden rounded-xl border border-[#e4e7e9]"><div className="grid grid-cols-[1fr_120px_100px] bg-[#f5f6f7] px-3 py-2 text-[9px] font-semibold uppercase text-[#7b8388]"><span>Action</span><span>Responsable</span><span>Échéance</span></div>{[1,2,3].map(row => <div key={row} className="grid grid-cols-[1fr_120px_100px] border-t border-[#eceeef] px-3 py-3"><div className="h-2.5 w-[78%] rounded bg-[#e9ecee]" /><div className="h-2.5 w-[70%] rounded bg-[#e9ecee]" /><div className="h-2.5 w-[65%] rounded bg-[#e9ecee]" /></div>)}</div></div> : <><div className="rounded-[16px] border border-[#e1e4e6] bg-white p-5"><div className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#737b80]">Synthèse</div><p className="mt-3 max-w-3xl text-[18px] font-medium leading-7 text-[#202a2f]">Le contenu reste lisible, sobre et structuré pour les interlocuteurs du deal.</p></div><div className="mt-4 grid gap-4"><div className="rounded-[16px] border border-[#e1e4e6] bg-white p-5"><div className="h-2.5 w-[88%] rounded bg-[#eceeef]" /><div className="mt-2 h-2.5 w-[72%] rounded bg-[#eceeef]" /><div className="mt-2 h-2.5 w-[81%] rounded bg-[#eceeef]" /></div></div></>}</div></div>
    </div></div></div>;
}
