"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileText, Loader2, Save, Send } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { emptyStageContent, type SD02Content, type SD03Content, type SD04Content, type SD05Content, type SDStageContent } from "@/lib/sd-stage-content";
import { SD_STAGE_META, type SDCode, type SDDocumentRecord } from "@/lib/sd-room-types";
import { cn } from "@/lib/utils";

type RoomResponse = { documents: SDDocumentRecord[]; room: { id: string; title: string } | null };
const CODES: SDCode[] = ["SD02", "SD03", "SD04", "SD05"];
const OPTIONAL = new Set<SDCode>(["SD03", "SD04"]);
const REQUIRED_BEFORE: Partial<Record<SDCode, SDCode[]>> = {
  SD02: ["SD01"],
  SD03: ["SD02"],
  SD04: ["SD02"],
  SD05: ["SD01", "SD02"],
};

function lines(value: string) { return value.split("\n").map(item => item.trim()).filter(Boolean); }
function textLines(value: string[]) { return value.join("\n"); }
function Area({ value, onChange, rows = 5, placeholder }: { value: string; onChange: (value: string) => void; rows?: number; placeholder?: string }) { return <textarea value={value} onChange={event => onChange(event.target.value)} rows={rows} placeholder={placeholder} className="w-full resize-y rounded-lg border border-input bg-background px-3 py-2 text-sm leading-6 outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" />; }
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <div className="space-y-2"><div><Label>{label}</Label>{hint ? <p className="mt-0.5 text-[11px] text-muted-foreground">{hint}</p> : null}</div>{children}</div>; }
function hydrate(code: SDCode, raw: Record<string, unknown> | undefined): SDStageContent { const base = emptyStageContent(code) as Record<string, unknown>; if (code === "SD03") return { ...base, ...(raw || {}), pilot: { ...(base.pilot as object), ...(((raw || {}).pilot as object) || {}) } } as SDStageContent; return { ...base, ...(raw || {}) } as SDStageContent; }

function SD02Form({ value, onChange }: { value: SD02Content; onChange: (value: SD02Content) => void }) {
  const set = <K extends keyof SD02Content>(key: K, next: SD02Content[K]) => onChange({ ...value, [key]: next });
  return <div className="grid gap-5 xl:grid-cols-2"><Card className="space-y-4 p-5"><Field label="Objectif commun"><Area value={value.objective} onChange={next => set("objective", next)} rows={5} /></Field><Field label="Résultat attendu"><Area value={value.successDefinition} onChange={next => set("successDefinition", next)} rows={4} /></Field><Field label="Actions / objectifs" hint="Une ligne : action | responsable | date | dépendance"><Area value={value.milestones.map(item => `${item.milestone} | ${item.owner} | ${item.dueDate} | ${item.dependency}`).join("\n")} onChange={next => set("milestones", lines(next).map(row => { const [milestone="", owner="", dueDate="", dependency=""] = row.split("|").map(item => item.trim()); return { milestone, owner, dueDate, dependency, status: "not_started" as const }; }))} rows={10} /></Field></Card><Card className="space-y-4 p-5"><Field label="Engagements client"><Area value={textLines(value.clientCommitments)} onChange={next => set("clientCommitments", lines(next))} /></Field><Field label="Engagements Gando"><Area value={textLines(value.gandoCommitments)} onChange={next => set("gandoCommitments", lines(next))} /></Field><Field label="Dépendances"><Area value={textLines(value.dependencies)} onChange={next => set("dependencies", lines(next))} /></Field><Field label="Risques"><Area value={textLines(value.risks)} onChange={next => set("risks", lines(next))} /></Field><Field label="Critères de réussite / clôture"><Area value={textLines(value.exitCriteria)} onChange={next => set("exitCriteria", lines(next))} /></Field></Card></div>;
}
function SD03Form({ value, onChange }: { value: SD03Content; onChange: (value: SD03Content) => void }) { const set = <K extends keyof SD03Content>(key: K, next: SD03Content[K]) => onChange({ ...value, [key]: next }); return <div className="grid gap-5 xl:grid-cols-2"><Card className="space-y-4 p-5"><Field label="Synthèse solution"><Area value={value.solutionSummary} onChange={next => set("solutionSummary", next)} rows={5} /></Field><Field label="Dans le périmètre"><Area value={textLines(value.scopeIn)} onChange={next => set("scopeIn", lines(next))} /></Field><Field label="Hors périmètre"><Area value={textLines(value.scopeOut)} onChange={next => set("scopeOut", lines(next))} /></Field><Field label="Intégrations"><Area value={textLines(value.integrations)} onChange={next => set("integrations", lines(next))} /></Field><Field label="Données requises"><Area value={textLines(value.dataRequirements)} onChange={next => set("dataRequirements", lines(next))} /></Field></Card><Card className="space-y-4 p-5"><Field label="Sécurité & conformité"><Area value={textLines(value.securityAndCompliance)} onChange={next => set("securityAndCompliance", lines(next))} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Périmètre pilote"><Input value={value.pilot.perimeter} onChange={event => set("pilot", { ...value.pilot, perimeter: event.target.value })} /></Field><Field label="Durée pilote"><Input value={value.pilot.duration} onChange={event => set("pilot", { ...value.pilot, duration: event.target.value })} /></Field></div><Field label="Métriques de succès du pilote"><Area value={textLines(value.pilot.successMetrics)} onChange={next => set("pilot", { ...value.pilot, successMetrics: lines(next) })} /></Field><Field label="Plan de déploiement"><Area value={textLines(value.deploymentPlan)} onChange={next => set("deploymentPlan", lines(next))} /></Field><Field label="Responsables techniques"><Area value={textLines(value.technicalOwners)} onChange={next => set("technicalOwners", lines(next))} /></Field></Card></div>; }
function SD04Form({ value, onChange }: { value: SD04Content; onChange: (value: SD04Content) => void }) { const set = <K extends keyof SD04Content>(key: K, next: SD04Content[K]) => onChange({ ...value, [key]: next }); return <div className="grid gap-5 xl:grid-cols-2"><Card className="space-y-4 p-5"><Field label="Synthèse de l’offre"><Area value={value.offerSummary} onChange={next => set("offerSummary", next)} rows={5} /></Field><Field label="Tarification" hint="Une ligne : produit | modèle | prix | notes"><Area value={value.pricing.map(item => `${item.item} | ${item.model} | ${item.price} | ${item.notes}`).join("\n")} onChange={next => set("pricing", lines(next).map(row => { const [item="", model="", price="", notes=""] = row.split("|").map(value => value.trim()); return { item, model, price, notes }; }))} rows={8} /></Field><Field label="Hypothèses"><Area value={textLines(value.assumptions)} onChange={next => set("assumptions", lines(next))} /></Field></Card><Card className="space-y-4 p-5"><Field label="Business case" hint="Une ligne : métrique | actuel | cible | valeur"><Area value={value.businessCase.map(item => `${item.metric} | ${item.baseline} | ${item.target} | ${item.value}`).join("\n")} onChange={next => set("businessCase", lines(next).map(row => { const [metric="", baseline="", target="", metricValue=""] = row.split("|").map(value => value.trim()); return { metric, baseline, target, value: metricValue }; }))} rows={7} /></Field><Field label="Conditions commerciales"><Area value={textLines(value.commercialTerms)} onChange={next => set("commercialTerms", lines(next))} /></Field><Field label="Étapes achats / procurement"><Area value={textLines(value.procurementSteps)} onChange={next => set("procurementSteps", lines(next))} /></Field><Field label="Validité de l’offre"><Input type="date" value={value.validityDate} onChange={event => set("validityDate", event.target.value)} /></Field></Card></div>; }
function SD05Form({ value, onChange }: { value: SD05Content; onChange: (value: SD05Content) => void }) { const set = <K extends keyof SD05Content>(key: K, next: SD05Content[K]) => onChange({ ...value, [key]: next }); return <div className="grid gap-5 xl:grid-cols-2"><Card className="space-y-4 p-5"><Field label="Synthèse contrat"><Area value={value.contractSummary} onChange={next => set("contractSummary", next)} rows={5} /></Field><Field label="Points juridiques" hint="Une ligne : sujet | open/in_review/approved | responsable | notes"><Area value={value.legalItems.map(item => `${item.topic} | ${item.status} | ${item.owner} | ${item.notes}`).join("\n")} onChange={next => set("legalItems", lines(next).map(row => { const [topic="", rawStatus="", owner="", notes=""] = row.split("|").map(value => value.trim()); const status = rawStatus === "approved" || rawStatus === "in_review" ? rawStatus : "open"; return { topic, status, owner, notes }; }))} rows={8} /></Field><Field label="Signataires" hint="Une ligne : nom | rôle | organisation"><Area value={value.signatories.map(item => `${item.name} | ${item.role} | ${item.organization}`).join("\n")} onChange={next => set("signatories", lines(next).map(row => { const [name="", role="", organization=""] = row.split("|").map(value => value.trim()); return { name, role, organization }; }))} /></Field></Card><Card className="space-y-4 p-5"><Field label="Étapes de signature"><Area value={textLines(value.signatureSteps)} onChange={next => set("signatureSteps", lines(next))} /></Field><Field label="Conditions finales"><Area value={textLines(value.finalConditions)} onChange={next => set("finalConditions", lines(next))} /></Field><Field label="Date de go-live"><Input type="date" value={value.goLiveDate} onChange={event => set("goLiveDate", event.target.value)} /></Field><Field label="Plan de handover"><Area value={textLines(value.handoverPlan)} onChange={next => set("handoverPlan", lines(next))} /></Field></Card></div>; }

export function SDRoomStageEditor({ dealId }: { dealId: string }) {
  const [data, setData] = useState<RoomResponse | null>(null);
  const [active, setActive] = useState<SDCode>("SD02");
  const [content, setContent] = useState<SDStageContent>(emptyStageContent("SD02") as SDStageContent);
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState(false);

  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/deals/${encodeURIComponent(dealId)}/sd-room`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || payload.error || "Chargement impossible"); setData(payload); const doc = payload.documents.find((item: SDDocumentRecord) => item.code === active); setContent(hydrate(active, doc?.content as Record<string, unknown>)); } catch (error) { toast.error(error instanceof Error ? error.message : "Chargement impossible"); } finally { setLoading(false); } }, [active, dealId]);
  useEffect(() => { void load(); }, [load]);
  const selectStage = (code: SDCode) => { setActive(code); const doc = data?.documents.find(item => item.code === code); setContent(hydrate(code, doc?.content as Record<string, unknown>)); };

  const current = data?.documents.find(item => item.code === active);
  const requiredBefore = REQUIRED_BEFORE[active] || [];
  const missingRequired = requiredBefore.filter(code => data?.documents.find(item => item.code === code)?.status !== "validated");
  const canPublish = missingRequired.length === 0;

  const save = async (publish: boolean) => { setWorking(true); try { const response = await fetch(`/api/deals/${encodeURIComponent(dealId)}/sd-room/document`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ code: active, content, publish }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || payload.error || "Enregistrement impossible"); setData(currentData => currentData ? { ...currentData, documents: currentData.documents.map(doc => doc.code === active ? payload.document : doc) } : currentData); setContent(hydrate(active, payload.document.content)); toast.success(publish ? `${active} publié dans la Room` : `${active} enregistré`); } catch (error) { toast.error(error instanceof Error ? error.message : "Enregistrement impossible"); } finally { setWorking(false); } };
  const title = useMemo(() => `${active} · ${SD_STAGE_META[active].title}`, [active]);
  if (loading && !data) return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;

  const requirementCopy = canPublish ? `${requiredBefore.join(" + ") || "Aucun prérequis"} validé · publication autorisée` : `${missingRequired.join(" + ")} à valider avant publication`;

  return <div className="page-shell min-h-screen p-5 lg:p-7"><div className="mx-auto max-w-[1500px] space-y-5"><header className="rounded-2xl border border-border bg-card p-5"><div className="text-xs font-bold uppercase tracking-[.15em] text-primary">Parcours de closing</div><h1 className="mt-1 text-2xl font-bold">SD02 → SD05</h1><p className="mt-2 text-sm text-muted-foreground">SD02 est le plan d’action. SD03 et SD04 sont facultatifs. SD05 est obligatoire et devient publiable dès que la Synthèse (SD01) et le Plan d’action (SD02) sont validés.</p></header><nav className="grid gap-2 md:grid-cols-4">{CODES.map(code => { const doc = data?.documents.find(item => item.code === code); const optional = OPTIONAL.has(code); return <button type="button" key={code} onClick={() => selectStage(code)} className={cn("rounded-xl border p-3 text-left", active === code ? "border-primary bg-primary/[.08]" : "border-border bg-card")}><div className="flex items-center justify-between"><span className="text-xs font-bold text-primary">{code}</span>{doc?.status === "validated" ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : null}</div><div className="mt-1 text-xs font-semibold">{SD_STAGE_META[code].title}</div><div className="mt-1 text-[10px] text-muted-foreground">{optional ? "Facultatif" : "Obligatoire"} · {doc?.status || "draft"}</div></button>; })}</nav><div className="flex flex-wrap items-center gap-3"><div><h2 className="text-lg font-bold">{title}</h2><p className="text-xs text-muted-foreground">{SD_STAGE_META[active].subtitle}</p></div><Badge variant="outline" className={canPublish ? "border-emerald-400/30 text-emerald-300" : "border-amber-400/30 text-amber-300"}>{requirementCopy}</Badge><div className="ml-auto flex gap-2"><Button variant="outline" onClick={() => void save(false)} disabled={working}>{working ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}Enregistrer</Button><Button onClick={() => void save(true)} disabled={working || !canPublish}>{working ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Publier</Button></div></div>{active === "SD02" ? <SD02Form value={content as SD02Content} onChange={setContent} /> : active === "SD03" ? <SD03Form value={content as SD03Content} onChange={setContent} /> : active === "SD04" ? <SD04Form value={content as SD04Content} onChange={setContent} /> : <SD05Form value={content as SD05Content} onChange={setContent} />}<Card className="p-5"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-primary" /><strong>Statut actuel</strong><Badge variant="outline">{current?.status || "draft"}</Badge><Badge variant="outline">{OPTIONAL.has(active) ? "Facultatif" : "Obligatoire"}</Badge></div>{current?.status === "validated" ? <p className="mt-2 text-sm text-emerald-300">Cette étape a été validée côté client. Une nouvelle publication repassera l’étape en « publié / à valider ».</p> : null}</Card></div></div>;
}
