"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronDown, ChevronUp, Loader2, Plus, Save, Send, Sparkles, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { MutualActionItem, SD02Content } from "@/lib/sd-stage-content";
import { createEmptySD02 } from "@/lib/sd-stage-content";
import type { SDDocumentRecord } from "@/lib/sd-room-types";

type RoomResponse = { documents: SDDocumentRecord[]; room: { id: string; title: string } | null };
type StepStatus = "not_started" | "in_progress" | "done";
type StepWorkstream = "business" | "technical" | "legal" | "procurement" | "other";
type StepOrganization = "joint" | "client" | "gando";

const EMPTY_STEP: MutualActionItem = { milestone: "", workstream: "business", organization: "joint", owner: "", dueDate: "", status: "not_started", dependency: "" };

function normalizeStep(item: Partial<MutualActionItem>): MutualActionItem {
  const status: StepStatus = item.status === "done" || item.status === "in_progress" ? item.status : "not_started";
  const workstream: StepWorkstream = item.workstream === "technical" || item.workstream === "legal" || item.workstream === "procurement" || item.workstream === "other" ? item.workstream : "business";
  const organization: StepOrganization = item.organization === "client" || item.organization === "gando" ? item.organization : "joint";
  return { milestone: item.milestone || "", workstream, organization, owner: item.owner || "", dueDate: item.dueDate || "", status, dependency: item.dependency || "" };
}

function normalizeContent(value: unknown): SD02Content {
  const stored = value && typeof value === "object" ? value as Partial<SD02Content> : {};
  return { ...createEmptySD02(), milestones: Array.isArray(stored.milestones) ? stored.milestones.map(normalizeStep) : [] };
}

function upsertDocument(documents: SDDocumentRecord[], next: SDDocumentRecord) {
  return documents.some(document => document.code === next.code)
    ? documents.map(document => document.code === next.code ? next : document)
    : [...documents, next];
}

function Select({ value, onChange, children, disabled = false }: { value: string; onChange: (value: string) => void; children: React.ReactNode; disabled?: boolean }) {
  return <select value={value} onChange={event => onChange(event.target.value)} disabled={disabled} className="h-9 rounded-lg border border-border bg-background px-2.5 text-xs font-medium outline-none focus:border-primary disabled:opacity-60">{children}</select>;
}

export function SD02PlanBuilder({ dealId }: { dealId: string }) {
  const [data, setData] = useState<RoomResponse | null>(null);
  const [content, setContent] = useState<SD02Content>(() => createEmptySD02());
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  const applyGeneratedDocument = useCallback((roomPayload: RoomResponse, document: SDDocumentRecord) => {
    setData({ ...roomPayload, documents: upsertDocument(roomPayload.documents, document) });
    setContent(normalizeContent(document.content));
    setAutoGenerated(true);
  }, []);

  const load = useCallback(async () => {
    setLoading(true);
    setAutoGenerated(false);
    try {
      const response = await fetch(`/api/deals/${encodeURIComponent(dealId)}/sd-room`, { cache: "no-store" });
      const payload = await response.json() as RoomResponse & { message?: string; error?: string };
      if (!response.ok) throw new Error(payload.message || payload.error || "Chargement impossible");

      const document = payload.documents.find(item => item.code === "SD02");
      const sd01 = payload.documents.find(item => item.code === "SD01");
      const next = normalizeContent(document?.content);
      setData(payload);
      setContent(next);

      if (!next.milestones.length && sd01 && document?.status !== "validated") {
        setGenerating(true);
        try {
          const generatedResponse = await fetch(`/api/deals/${encodeURIComponent(dealId)}/sd-room/generate-sd02`, {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ force: false }),
          });
          const generatedPayload = await generatedResponse.json();
          if (generatedResponse.ok && generatedPayload.document) applyGeneratedDocument(payload, generatedPayload.document as SDDocumentRecord);
        } finally { setGenerating(false); }
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Chargement impossible");
    } finally { setLoading(false); }
  }, [dealId, applyGeneratedDocument]);

  useEffect(() => { void load(); }, [load]);

  const sd02 = data?.documents.find(item => item.code === "SD02");
  const locked = sd02?.status === "validated";
  const completed = useMemo(() => content.milestones.filter(step => step.status === "done").length, [content.milestones]);

  const updateStep = <K extends keyof MutualActionItem>(index: number, key: K, value: MutualActionItem[K]) => setContent(current => ({
    ...current,
    milestones: current.milestones.map((step, currentIndex) => currentIndex === index ? { ...step, [key]: value } : step),
  }));
  const addStep = () => setContent(current => ({ ...current, milestones: [...current.milestones, { ...EMPTY_STEP }] }));
  const removeStep = (index: number) => setContent(current => ({ ...current, milestones: current.milestones.filter((_, currentIndex) => currentIndex !== index) }));
  const moveStep = (index: number, direction: -1 | 1) => setContent(current => {
    const target = index + direction;
    if (target < 0 || target >= current.milestones.length) return current;
    const next = [...current.milestones];
    [next[index], next[target]] = [next[target], next[index]];
    return { ...current, milestones: next };
  });

  const regenerate = async () => {
    if (locked) return;
    if (content.milestones.length && !window.confirm("Remplacer les prochaines étapes actuelles par une nouvelle proposition générée depuis SD01 ?")) return;
    setGenerating(true);
    try {
      const response = await fetch(`/api/deals/${encodeURIComponent(dealId)}/sd-room/generate-sd02`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ force: true }),
      });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.message || payload.error || "Génération impossible");
      if (!payload.document) throw new Error("Aucun SD02 généré.");
      const document = payload.document as SDDocumentRecord;
      setData(current => current ? { ...current, documents: upsertDocument(current.documents, document) } : current);
      setContent(normalizeContent(document.content));
      setAutoGenerated(true);
      toast.success("Prochaines étapes générées depuis SD01");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Génération impossible");
    } finally { setGenerating(false); }
  };

  const save = async (publish: boolean) => {
    const milestones = content.milestones.map(normalizeStep).filter(step => step.milestone.trim());
    if (!milestones.length) { toast.error("Ajoute au moins une prochaine étape."); return; }
    const cleaned: SD02Content = { ...createEmptySD02(), milestones };
    setWorking(true);
    try {
      const response = await fetch(`/api/deals/${encodeURIComponent(dealId)}/sd-room/document`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ code: "SD02", content: cleaned, publish }),
      });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.message || payload.error || "Enregistrement impossible");
      const document = payload.document as SDDocumentRecord;
      setData(current => current ? { ...current, documents: upsertDocument(current.documents, document) } : current);
      setContent(normalizeContent(document.content));
      setAutoGenerated(false);
      toast.success(publish ? "Prochaines étapes publiées" : "Prochaines étapes enregistrées");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Enregistrement impossible");
    } finally { setWorking(false); }
  };

  if (loading && !data) return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;

  return <div className="min-h-screen bg-muted/20 px-4 py-6 lg:px-7 lg:py-8">
    <div className="mx-auto max-w-[1040px] space-y-4">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <div className="text-[10px] font-black uppercase tracking-[0.16em] text-primary">SD02 · Prochaines étapes</div>
          <h1 className="mt-1 text-2xl font-black tracking-[-0.035em]">Prochaines étapes</h1>
          <p className="mt-1 text-sm text-muted-foreground">Uniquement les actions nécessaires pour faire avancer le deal.</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Badge variant="outline">{completed}/{content.milestones.length} terminée{completed > 1 ? "s" : ""}</Badge>
          {(autoGenerated || sd02?.source_mode === "agent" || sd02?.source_mode === "mixed") && content.milestones.length ? <Badge variant="outline" className="border-primary/30 text-primary"><Sparkles className="mr-1 h-3.5 w-3.5" />Généré depuis SD01</Badge> : null}
          {locked ? <Badge variant="outline" className="border-emerald-500/30 text-emerald-600"><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Validé client</Badge> : null}
          <Button variant="outline" onClick={() => void regenerate()} disabled={working || generating || locked}>{generating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}Régénérer</Button>
          <Button variant="outline" onClick={() => void save(false)} disabled={working || generating || locked}><Save className="mr-2 h-4 w-4" />Enregistrer</Button>
          <Button onClick={() => void save(true)} disabled={working || generating || locked}><Send className="mr-2 h-4 w-4" />Publier</Button>
        </div>
      </div>

      {generating ? <Card className="border-primary/20 bg-primary/5 p-4"><div className="flex items-center gap-3"><Loader2 className="h-4 w-4 animate-spin text-primary" /><div><div className="text-sm font-bold">Génération des prochaines étapes</div><div className="text-xs text-muted-foreground">Le SD01 est utilisé uniquement pour proposer les actions utiles.</div></div></div></Card> : null}

      <Card className="overflow-hidden border-border/80 bg-card p-0 shadow-sm">
        <div className="flex items-center justify-between gap-3 border-b border-border bg-muted/25 px-6 py-4 sm:px-9">
          <div><div className="text-sm font-bold">Plan d’action</div><div className="text-[11px] text-muted-foreground">Une ligne = une vraie prochaine étape.</div></div>
          <Button type="button" variant="outline" size="sm" onClick={addStep} disabled={locked}><Plus className="mr-1 h-3.5 w-3.5" />Ajouter</Button>
        </div>

        <div className="space-y-3 p-5 sm:p-7">
          {content.milestones.map((step, index) => <div key={index} className="group rounded-xl border border-border bg-background p-4">
            <div className="flex items-start gap-3">
              <div className="mt-1 grid h-7 w-7 shrink-0 place-items-center rounded-full bg-primary text-[10px] font-bold text-primary-foreground">{index + 1}</div>
              <div className="min-w-0 flex-1">
                <Input value={step.milestone} onChange={event => updateStep(index, "milestone", event.target.value)} placeholder="Décrire la prochaine étape…" className="h-auto border-0 bg-transparent p-0 text-[15px] font-semibold shadow-none focus-visible:ring-0" disabled={locked} />
                <textarea value={step.dependency} onChange={event => updateStep(index, "dependency", event.target.value)} rows={2} placeholder="Détail ou dépendance éventuelle…" className="mt-2 w-full resize-none border-0 bg-transparent p-0 text-sm leading-6 text-muted-foreground outline-none placeholder:text-muted-foreground/50 disabled:opacity-70" disabled={locked} />
                <div className="mt-3 flex flex-wrap items-center gap-2">
                  <Input value={step.owner} onChange={event => updateStep(index, "owner", event.target.value)} placeholder="Responsable" className="h-9 w-36 text-xs" disabled={locked} />
                  <Input type="date" value={step.dueDate} onChange={event => updateStep(index, "dueDate", event.target.value)} className="h-9 w-40 text-xs" disabled={locked} />
                  <Select value={step.status} onChange={value => updateStep(index, "status", value as StepStatus)} disabled={locked}><option value="not_started">À faire</option><option value="in_progress">En cours</option><option value="done">Terminé</option></Select>
                  <Select value={step.organization} onChange={value => updateStep(index, "organization", value as StepOrganization)} disabled={locked}><option value="joint">Commun</option><option value="client">Client</option><option value="gando">Gando</option></Select>
                  <Select value={step.workstream} onChange={value => updateStep(index, "workstream", value as StepWorkstream)} disabled={locked}><option value="business">Business</option><option value="technical">Technique</option><option value="legal">Juridique</option><option value="procurement">Achats</option><option value="other">Autre</option></Select>
                </div>
              </div>
              <div className="flex shrink-0 items-center opacity-60 transition group-hover:opacity-100">
                <Button type="button" variant="ghost" size="icon" className="h-8 w-8" onClick={() => moveStep(index, -1)} disabled={index === 0 || locked}><ChevronUp className="h-4 w-4" /></Button>
                <Button type="button" variant="ghost" size="icon" className="h-8 w-8" onClick={() => moveStep(index, 1)} disabled={index === content.milestones.length - 1 || locked}><ChevronDown className="h-4 w-4" /></Button>
                <Button type="button" variant="ghost" size="icon" className="h-8 w-8 text-destructive" onClick={() => removeStep(index)} disabled={locked}><Trash2 className="h-4 w-4" /></Button>
              </div>
            </div>
          </div>)}

          {!content.milestones.length && !generating ? <div className="rounded-xl border border-dashed border-border p-8 text-center"><div className="text-sm font-semibold">Aucune prochaine étape</div><p className="mt-1 text-xs text-muted-foreground">Génère-les depuis SD01 ou ajoute-les manuellement.</p><div className="mt-4 flex justify-center gap-2"><Button variant="outline" onClick={() => void regenerate()}><Sparkles className="mr-2 h-4 w-4" />Générer</Button><Button variant="outline" onClick={addStep}><Plus className="mr-2 h-4 w-4" />Ajouter</Button></div></div> : null}
        </div>
      </Card>
    </div>
  </div>;
}
