create table if not exists public.gando_source_records (
  id bigint generated by default as identity primary key,
  source_project text not null,
  source_schema text not null default 'public',
  source_table text not null,
  source_id text not null,
  payload jsonb not null,
  source_updated_at timestamptz,
  sync_run_id uuid not null,
  synced_at timestamptz not null default now(),
  unique (source_project, source_schema, source_table, source_id)
);

create index if not exists gando_source_records_lookup_idx
  on public.gando_source_records (source_project, source_schema, source_table);

create index if not exists gando_source_records_updated_at_idx
  on public.gando_source_records (source_project, source_schema, source_table, source_updated_at desc);

create table if not exists public.gando_source_sync_state (
  id bigint generated by default as identity primary key,
  source_project text not null,
  source_schema text not null default 'public',
  source_table text not null,
  id_column text not null default 'id',
  status text not null default 'idle' check (status in ('idle', 'running', 'success', 'error')),
  rows_synced integer not null default 0,
  last_started_at timestamptz,
  last_completed_at timestamptz,
  last_error text,
  last_run_id uuid,
  updated_at timestamptz not null default now(),
  unique (source_project, source_schema, source_table)
);

alter table public.gando_source_records enable row level security;
alter table public.gando_source_sync_state enable row level security;

comment on table public.gando_source_records is
  'Miroir brut, serveur uniquement, des lignes lues depuis le Supabase principal Gando.';

comment on table public.gando_source_sync_state is
  'Etat des synchronisations du Supabase principal Gando vers le Sales Cockpit.';
